kind: pipeline
type: docker
name: auto-tag

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: build
    image: alpine/git
    environment:
      USERNAME:
        from_secret: github_username
      EMAIL:
        from_secret: github_email
    commands:
      - git config --local user.name "${USERNAME}"
      - git config --local user.email "${EMAIL}"
      - export DRONE_TAG=pdf-release-v${DRONE_BUILD_NUMBER}
      - git tag -f $DRONE_TAG
      - git push -f $DRONE_TAG

---

kind: pipeline
type: docker
name: tickets book

trigger:
  event:
    - tag

steps:
  - name: build
    image: emptyshadow/eltech-book-builder
    commands:
      - gitbook install
      - gitbook build
      - gitbook pdf
  - name: release pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: ./_book
  - name: release books
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - ./book.pdf
      file_exists: overwrite